In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import os as os

In [14]:
df = pd.read_csv("ds/pr2_ds")

In [12]:
os.getcwd()

'c:\\Learning\\Libraries\\Pandas\\analysis'

In [15]:
df

   Unnamed: 0  OrderID Customer    City   Product  Quantity  Price   OrderDate
0           0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1           1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2           2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3           3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4           4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5           5      106     Neha    Pune     Mouse         2    600  2024-01-13
6           6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7           7      108     Riya    Pune     Mouse         2    550  2024-01-18
8           8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9           9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [24]:
df.drop("Unnamed: 0",axis=1)

   OrderID Customer    City   Product  Quantity  Price   OrderDate
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [29]:
df.drop(df.columns[0],axis=1)

   OrderID Customer    City   Product  Quantity  Price   OrderDate
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [33]:
df.groupby("Product").agg(
    {"Quantity":"sum",
    "Price":"sum"}
).sort_values(by="Price",ascending=False)

          Quantity   Price
Product
Laptop           4  206000
Keyboard         5    4500
Mouse            6    1650

In [34]:
df.groupby("Product").agg(
    {"Price":"mean"}
).sort_values(by="Price",ascending=False)

            Price
Product
Laptop    51500.0
Keyboard   1500.0
Mouse       550.0

In [36]:
df.groupby("City").agg(
    {"OrderID":"count"}
).sort_values(by="OrderID",ascending=False)

        OrderID
City
Delhi         5
Mumbai        3
Pune          2

In [38]:
df.groupby("Product").agg(
    Quantity = ("Quantity","sum"),
    Count = ("Product","count")
).sort_values(by="Quantity",ascending=False)

          Quantity  Count
Product
Mouse            6      3
Keyboard         5      3
Laptop           4      4

In [39]:
df.groupby("Customer").agg(
    {"Price":"sum"}
).sort_values(by="Price",ascending=False).head(1)

           Price
Customer
Riya      102550

In [41]:
df.groupby("City").agg(
    {"OrderID":"count"}
).sort_values(by="OrderID",ascending=False).head(1)

       OrderID
City
Delhi        5

In [45]:
df.groupby("Product")["Quantity"].sum().head(1)

Product
Keyboard    5
Name: Quantity, dtype: int64

In [47]:
df[["Price"]].sum()

Price    212150
dtype: int64

In [48]:
df.sort_values(by="Price",ascending=False).head(3)

   Unnamed: 0  OrderID Customer   City Product  Quantity  Price   OrderDate
9           9      110     Aman  Delhi  Laptop         1  53000  2024-01-22
3           3      104     Riya  Delhi  Laptop         1  52000  2024-01-10
6           6      107    Karan  Delhi  Laptop         1  51000  2024-01-15

In [51]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [52]:
df

   OrderID Customer    City   Product  Quantity  Price   OrderDate
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool